CC = g++
CFLAGS = -g -Wall -o3 -fopenmp -std=c++11
SRCS = main_i_console.cpp
PROG = main_i_console

build: main_i_console.cpp
	$(CC) $(CFLAGS) -o $(PROG) $(SRCS)

run:
	./$(PROG)

clear:
	rm -rf out

